import type { InboxSeedThread } from "@nudle/ui/inbox-view";

const studentThreads: InboxSeedThread[] = [
  {
    id: "s1",
    name: "Dr. M. Sibanda",
    role: "General Science",
    tags: ["Academic", "Unread"],
    time: "11:21",
    subject: "Lab write-up due Friday",
    preview: "Please submit the Form 3 practical before 16:00. Late work loses 10%.",
    section: "teachers",
  },
  {
    id: "s2",
    name: "Ms. L. Moyo",
    role: "French",
    tags: ["Academic"],
    time: "09:41",
    subject: "Oral practice pairs",
    preview: "You'll present with Tendai tomorrow. Rehearse the market dialogue.",
    section: "teachers",
  },
  {
    id: "s3",
    name: "Mr. T. Ncube",
    role: "Mathematics",
    tags: ["Unread"],
    time: "08:17",
    subject: "Algebra quiz moved",
    preview: "The quiz is now Thursday. Review completing the square.",
    section: "teachers",
  },
  {
    id: "s4",
    name: "Mrs. P. Chikwanha",
    role: "English Literature",
    tags: ["Academic"],
    time: "Yesterday",
    subject: "Essay feedback",
    preview: "Strong opening on Things Fall Apart — tighten the third paragraph.",
    section: "teachers",
  },
  {
    id: "s5",
    name: "Tendai Moyo",
    role: "Classmate",
    tags: ["Unread"],
    time: "Yesterday",
    subject: "Science notes",
    preview: "I photographed the board after last period. Want me to send them?",
    section: "classmates",
  },
  {
    id: "s6",
    name: "Nyasha Chirwa",
    role: "Classmate",
    tags: [],
    time: "Mon",
    subject: "History group",
    preview: "Can we meet at the library at 14:30 to finish the timeline?",
    section: "classmates",
  },
  {
    id: "s7",
    name: "Farai Dube",
    role: "Classmate",
    tags: [],
    time: "Tue",
    subject: "Football kit",
    preview: "Coach said bring both jerseys on Friday for the inter-house match.",
    section: "classmates",
  },
  {
    id: "s8",
    name: "Academic Office",
    role: "Announcements",
    tags: ["School-wide"],
    time: "Sun",
    subject: "Midterm timetable",
    preview: "The Term 3 exam schedule is up. Check Calendar for your papers.",
    section: "announcements",
  },
  {
    id: "s9",
    name: "Library Services",
    role: "Announcements",
    tags: ["School-wide"],
    time: "Fri",
    subject: "Extended hours",
    preview: "Library is 24/7 from Monday for the exam period. Bring your ID.",
    section: "announcements",
  },
];

const parentThreads: InboxSeedThread[] = [
  {
    id: "p1",
    name: "Mrs. P. Chikwanha",
    role: "Form teacher",
    tags: ["Pastoral", "Unread"],
    time: "11:21",
    subject: "Parents' evening",
    preview: "Please confirm Tuesday 17:30 for the Form 3 progress meeting.",
    section: "teachers",
  },
  {
    id: "p2",
    name: "Mr. T. Ncube",
    role: "Mathematics",
    tags: ["Academic"],
    time: "09:41",
    subject: "Support class",
    preview: "Your child is invited to Thursday's extra maths session, 15:00–16:00.",
    section: "teachers",
  },
  {
    id: "p3",
    name: "Dr. M. Sibanda",
    role: "General Science",
    tags: ["Unread"],
    time: "08:17",
    subject: "Field trip consent",
    preview: "The ecology visit is 24 September. Please sign the form on Family.",
    section: "teachers",
  },
  {
    id: "p4",
    name: "Bursar",
    role: "Fees",
    tags: ["Fees"],
    time: "Yesterday",
    subject: "Term 3 balance",
    preview: "A reminder that the remaining fees are due by Friday 26 September.",
    section: "staff",
  },
  {
    id: "p5",
    name: "Helen Brooks",
    role: "Parent",
    tags: [],
    time: "Mon",
    subject: "Lift share",
    preview: "Are you going to athletics on Friday? Happy to take an extra student.",
    section: "parents",
  },
  {
    id: "p6",
    name: "Rudo Mhlanga",
    role: "Parent",
    tags: [],
    time: "Tue",
    subject: "Uniform shop",
    preview: "They're restocking blazers tomorrow morning if you still need one.",
    section: "parents",
  },
  {
    id: "p7",
    name: "Academic Office",
    role: "Announcements",
    tags: ["School-wide", "Unread"],
    time: "Sun",
    subject: "Inter-house athletics",
    preview: "All forms assemble at 08:00. Parents welcome from 10:00.",
    section: "announcements",
  },
  {
    id: "p8",
    name: "Office",
    role: "Announcements",
    tags: ["School-wide"],
    time: "Fri",
    subject: "INSET Monday",
    preview: "School closed to students Monday. Aftercare is not available.",
    section: "announcements",
  },
  {
    id: "p9",
    name: "Ms. L. Moyo",
    role: "French",
    tags: ["Academic"],
    time: "Yesterday",
    subject: "Oral exam",
    preview: "The Form 3 orals are next week. A revision sheet is on the portal.",
    section: "teachers",
  },
];

const organizationThreads: InboxSeedThread[] = [
  {
    id: "o1",
    name: "Tafadzwa Sibanda",
    role: "Bursar",
    tags: ["Fees", "Unread"],
    time: "11:21",
    subject: "Fee bridging drawdown",
    preview: "We can disburse against next week's collection if the pack is signed.",
    section: "staff",
  },
  {
    id: "o2",
    name: "Chipo Zulu",
    role: "Head of Department",
    tags: ["Academic"],
    time: "09:41",
    subject: "Textbook order",
    preview: "Confirm the Form 4 literature set before we raise the purchase order.",
    section: "staff",
  },
  {
    id: "o3",
    name: "Nyasha Chirwa",
    role: "Science",
    tags: ["Unread"],
    time: "08:17",
    subject: "Lab equipment quote",
    preview: "The bunsen replacements came in 12% over budget. Can finance approve?",
    section: "staff",
  },
  {
    id: "o4",
    name: "Blessing Chirwa",
    role: "Form teacher",
    tags: [],
    time: "Yesterday",
    subject: "Trip insurance",
    preview: "Need the cover note for the Form 1 Blue outing before Friday.",
    section: "staff",
  },
  {
    id: "o5",
    name: "Office",
    role: "Announcements",
    tags: ["School-wide"],
    time: "Sun",
    subject: "Payroll cut-off",
    preview: "Timesheets for this month close Wednesday at 12:00.",
    section: "announcements",
  },
  {
    id: "o6",
    name: "Academic Office",
    role: "Announcements",
    tags: ["School-wide"],
    time: "Fri",
    subject: "INSET Monday",
    preview: "Staff briefing at 07:30 in the hall. Registers close at 07:45.",
    section: "announcements",
  },
];

export function studentInboxThreads(role: "student" | "parent" | "organization"): InboxSeedThread[] {
  if (role === "parent") return parentThreads;
  if (role === "organization") return organizationThreads;
  return studentThreads;
}
